<?php

use Illuminate\Database\Seeder;
use App\Municipality;
class MunicipalitiesTableSeeder extends Seeder
{

    public function run()
    {
        Municipality::create(['name' =>'Abriaquí','departament_id'=>1]);
        Municipality::create(['name' =>'Abejorral','departament_id'=>1]);
        Municipality::create(['name' =>'Acacías','departament_id'=>16]);
        Municipality::create(['name' =>'Acandí','departament_id'=>12]);
        Municipality::create(['name' =>'Acevedo','departament_id'=>13]);
        Municipality::create(['name' =>'Achí','departament_id'=>4]);
        Municipality::create(['name' =>'Agrado','departament_id'=>13]);
        Municipality::create(['name' =>'Agua de Dios','departament_id'=>11]);
        Municipality::create(['name' =>'Aguachica','departament_id'=>9]);
        Municipality::create(['name' =>'Aguada','departament_id'=>21]);
        Municipality::create(['name' =>'Aguadas','departament_id'=>6]);
        Municipality::create(['name' =>'Aguazul','departament_id'=>26]);
        Municipality::create(['name' =>'Agustín Codazzi','departament_id'=>9]);
        Municipality::create(['name' =>'Aipe','departament_id'=>13]);
        Municipality::create(['name' =>'Albania','departament_id'=>7]);
        Municipality::create(['name' =>'Albania','departament_id'=>14]);
        Municipality::create(['name' =>'Albania','departament_id'=>21]);
        Municipality::create(['name' =>'Albán','departament_id'=>11]);
        Municipality::create(['name' =>'Albán (San José)','departament_id'=>17]);
        Municipality::create(['name' =>'Alcalá','departament_id'=>24]);
        Municipality::create(['name' =>'Alejandria','departament_id'=>1]);
        Municipality::create(['name' =>'Algarrobo','departament_id'=>15]);
        Municipality::create(['name' =>'Algeciras','departament_id'=>13]);
        Municipality::create(['name' =>'Almaguer','departament_id'=>8]);
        Municipality::create(['name' =>'Almeida','departament_id'=>5]);
        Municipality::create(['name' =>'Alpujarra','departament_id'=>23]);
        Municipality::create(['name' =>'Altamira','departament_id'=>13]);
        Municipality::create(['name' =>'Alto Baudó (Pie de Pato)','departament_id'=>12]);
        Municipality::create(['name' =>'Altos del Rosario','departament_id'=>4]);
        Municipality::create(['name' =>'Alvarado','departament_id'=>23]);
        Municipality::create(['name' =>'Amagá','departament_id'=>1]);
        Municipality::create(['name' =>'Amalfi','departament_id'=>1]);
        Municipality::create(['name' =>'Ambalema','departament_id'=>23]);
        Municipality::create(['name' =>'Anapoima','departament_id'=>11]);
        Municipality::create(['name' =>'Ancuya','departament_id'=>17]);
        Municipality::create(['name' =>'Andalucía','departament_id'=>24]);
        Municipality::create(['name' =>'Andes','departament_id'=>1]);
        Municipality::create(['name' =>'Angelópolis','departament_id'=>1]);
        Municipality::create(['name' =>'Angostura','departament_id'=>1]);
        Municipality::create(['name' =>'Anolaima','departament_id'=>11]);
        Municipality::create(['name' =>'Anorí','departament_id'=>1]);
        Municipality::create(['name' =>'Anserma','departament_id'=>6]);
        Municipality::create(['name' =>'Ansermanuevo','departament_id'=>24]);
        Municipality::create(['name' =>'Anzoátegui','departament_id'=>23]);
        Municipality::create(['name' =>'Anzá','departament_id'=>1]);
        Municipality::create(['name' =>'Apartadó','departament_id'=>1]);
        Municipality::create(['name' =>'Apulo','departament_id'=>11]);
        Municipality::create(['name' =>'Apía','departament_id'=>20]);
        Municipality::create(['name' =>'Aquitania','departament_id'=>5]);
        Municipality::create(['name' =>'Aracataca','departament_id'=>15]);
        Municipality::create(['name' =>'Aranzazu','departament_id'=>6]);
        Municipality::create(['name' =>'Aratoca','departament_id'=>21]);
        Municipality::create(['name' =>'Arauca','departament_id'=>25]);
        Municipality::create(['name' =>'Arauquita','departament_id'=>25]);
        Municipality::create(['name' =>'Arbeláez','departament_id'=>11]);
        Municipality::create(['name' =>'Arboleda (Berruecos)','departament_id'=>17]);
        Municipality::create(['name' =>'Arboledas','departament_id'=>18]);
        Municipality::create(['name' =>'Arboletes','departament_id'=>1]);
        Municipality::create(['name' =>'Arcabuco','departament_id'=>5]);
        Municipality::create(['name' =>'Arenal','departament_id'=>4]);
        Municipality::create(['name' =>'Argelia','departament_id'=>1]);
        Municipality::create(['name' =>'Argelia','departament_id'=>8]);
        Municipality::create(['name' =>'Argelia','departament_id'=>24]);
        Municipality::create(['name' =>'Ariguaní (El Difícil)','departament_id'=>15]);
        Municipality::create(['name' =>'Arjona','departament_id'=>4]);
        Municipality::create(['name' =>'Armenia','departament_id'=>1]);
        Municipality::create(['name' =>'Armenia','departament_id'=>19]);
        Municipality::create(['name' =>'Armero (Guayabal)','departament_id'=>23]);
        Municipality::create(['name' =>'Arroyohondo','departament_id'=>4]);
        Municipality::create(['name' =>'Astrea','departament_id'=>9]);
        Municipality::create(['name' =>'Ataco','departament_id'=>23]);
        Municipality::create(['name' =>'Atrato (Yuto)','departament_id'=>12]);
        Municipality::create(['name' =>'Ayapel','departament_id'=>10]);
        Municipality::create(['name' =>'Bagadó','departament_id'=>12]);
        Municipality::create(['name' =>'Bahía Solano (Mútis)','departament_id'=>12]);
        Municipality::create(['name' =>'Bajo Baudó (Pizarro)','departament_id'=>12]);
        Municipality::create(['name' =>'Balboa','departament_id'=>8]);
        Municipality::create(['name' =>'Balboa','departament_id'=>20]);
        Municipality::create(['name' =>'Baranoa','departament_id'=>2]);
        Municipality::create(['name' =>'Baraya','departament_id'=>13]);
        Municipality::create(['name' =>'Barbacoas','departament_id'=>17]);
        Municipality::create(['name' =>'Barbosa','departament_id'=>1]);
        Municipality::create(['name' =>'Barbosa','departament_id'=>21]);
        Municipality::create(['name' =>'Barichara','departament_id'=>21]);
        Municipality::create(['name' =>'Barranca de Upía','departament_id'=>16]);
        Municipality::create(['name' =>'Barrancabermeja','departament_id'=>21]);
        Municipality::create(['name' =>'Barrancas','departament_id'=>14]);
        Municipality::create(['name' =>'Barranco de Loba','departament_id'=>4]);
        Municipality::create(['name' =>'Barranquilla','departament_id'=>2]);
        Municipality::create(['name' =>'Becerríl','departament_id'=>9]);
        Municipality::create(['name' =>'Belalcázar','departament_id'=>6]);
        Municipality::create(['name' =>'Bello','departament_id'=>1]);
        Municipality::create(['name' =>'Belmira','departament_id'=>1]);
        Municipality::create(['name' =>'Beltrán','departament_id'=>11]);
        Municipality::create(['name' =>'Belén','departament_id'=>5]);
        Municipality::create(['name' =>'Belén','departament_id'=>17]);
        Municipality::create(['name' =>'Belén de Bajirá','departament_id'=>12]);
        Municipality::create(['name' =>'Belén de Umbría','departament_id'=>20]);
        Municipality::create(['name' =>'Belén de los Andaquíes','departament_id'=>7]);
        Municipality::create(['name' =>'Berbeo','departament_id'=>5]);
        Municipality::create(['name' =>'Betania','departament_id'=>1]);
        Municipality::create(['name' =>'Beteitiva','departament_id'=>5]);
        Municipality::create(['name' =>'Betulia','departament_id'=>1]);
        Municipality::create(['name' =>'Betulia','departament_id'=>21]);
        Municipality::create(['name' =>'Bituima','departament_id'=>11]);
        Municipality::create(['name' =>'Boavita','departament_id'=>5]);
        Municipality::create(['name' =>'Bochalema','departament_id'=>18]);
        Municipality::create(['name' =>'Bogotá D.C.','departament_id'=>3]);
        Municipality::create(['name' =>'Bojacá','departament_id'=>11]);
        Municipality::create(['name' =>'Bojayá (Bellavista)','departament_id'=>12]);
        Municipality::create(['name' =>'Bolívar','departament_id'=>1]);
        Municipality::create(['name' =>'Bolívar','departament_id'=>8]);
        Municipality::create(['name' =>'Bolívar','departament_id'=>21]);
        Municipality::create(['name' =>'Bolívar','departament_id'=>24]);
        Municipality::create(['name' =>'Bosconia','departament_id'=>9]);
        Municipality::create(['name' =>'Boyacá','departament_id'=>5]);
        Municipality::create(['name' =>'Briceño','departament_id'=>1]);
        Municipality::create(['name' =>'Briceño','departament_id'=>5]);
        Municipality::create(['name' =>'Bucaramanga','departament_id'=>21]);
        Municipality::create(['name' =>'Bucarasica','departament_id'=>18]);
        Municipality::create(['name' =>'Buenaventura','departament_id'=>24]);
        Municipality::create(['name' =>'Buenavista','departament_id'=>5]);
        Municipality::create(['name' =>'Buenavista','departament_id'=>10]);
        Municipality::create(['name' =>'Buenavista','departament_id'=>19]);
        Municipality::create(['name' =>'Buenavista','departament_id'=>22]);
        Municipality::create(['name' =>'Buenos Aires','departament_id'=>8]);
        Municipality::create(['name' =>'Buesaco','departament_id'=>17]);
        Municipality::create(['name' =>'Buga','departament_id'=>24]);
        Municipality::create(['name' =>'Bugalagrande','departament_id'=>24]);
        Municipality::create(['name' =>'Burítica','departament_id'=>1]);
        Municipality::create(['name' =>'Busbanza','departament_id'=>5]);
        Municipality::create(['name' =>'Cabrera','departament_id'=>11]);
        Municipality::create(['name' =>'Cabrera','departament_id'=>21]);
        Municipality::create(['name' =>'Cabuyaro','departament_id'=>16]);
        Municipality::create(['name' =>'Cachipay','departament_id'=>11]);
        Municipality::create(['name' =>'Caicedo','departament_id'=>1]);
        Municipality::create(['name' =>'Caicedonia','departament_id'=>24]);
        Municipality::create(['name' =>'Caimito','departament_id'=>22]);
        Municipality::create(['name' =>'Cajamarca','departament_id'=>23]);
        Municipality::create(['name' =>'Cajibío','departament_id'=>8]);
        Municipality::create(['name' =>'Cajicá','departament_id'=>11]);
        Municipality::create(['name' =>'Calamar','departament_id'=>4]);
        Municipality::create(['name' =>'Calamar','departament_id'=>31]);
        Municipality::create(['name' =>'Calarcá','departament_id'=>19]);
        Municipality::create(['name' =>'Caldas','departament_id'=>1]);
        Municipality::create(['name' =>'Caldas','departament_id'=>5]);
        Municipality::create(['name' =>'Caldono','departament_id'=>8]);
        Municipality::create(['name' =>'California','departament_id'=>21]);
        Municipality::create(['name' =>'Calima (Darién)','departament_id'=>24]);
        Municipality::create(['name' =>'Caloto','departament_id'=>8]);
        Municipality::create(['name' =>'Calí','departament_id'=>24]);
        Municipality::create(['name' =>'Campamento','departament_id'=>1]);
        Municipality::create(['name' =>'Campo de la Cruz','departament_id'=>2]);
        Municipality::create(['name' =>'Campoalegre','departament_id'=>13]);
        Municipality::create(['name' =>'Campohermoso','departament_id'=>5]);
        Municipality::create(['name' =>'Canalete','departament_id'=>10]);
        Municipality::create(['name' =>'Candelaria','departament_id'=>2]);
        Municipality::create(['name' =>'Candelaria','departament_id'=>24]);
        Municipality::create(['name' =>'Cantagallo','departament_id'=>4]);
        Municipality::create(['name' =>'Cantón de San Pablo','departament_id'=>12]);
        Municipality::create(['name' =>'Caparrapí','departament_id'=>11]);
        Municipality::create(['name' =>'Capitanejo','departament_id'=>21]);
        Municipality::create(['name' =>'Caracolí','departament_id'=>1]);
        Municipality::create(['name' =>'Caramanta','departament_id'=>1]);
        Municipality::create(['name' =>'Carcasí','departament_id'=>21]);
        Municipality::create(['name' =>'Carepa','departament_id'=>1]);
        Municipality::create(['name' =>'Carmen de Apicalá','departament_id'=>23]);
        Municipality::create(['name' =>'Carmen de Carupa','departament_id'=>11]);
        Municipality::create(['name' =>'Carmen de Viboral','departament_id'=>1]);
        Municipality::create(['name' =>'Carmen del Darién (CURBARADÓ)','departament_id'=>12]);
        Municipality::create(['name' =>'Carolina','departament_id'=>1]);
        Municipality::create(['name' =>'Cartagena','departament_id'=>4]);
        Municipality::create(['name' =>'Cartagena del Chairá','departament_id'=>7]);
        Municipality::create(['name' =>'Cartago','departament_id'=>24]);
        Municipality::create(['name' =>'Carurú','departament_id'=>32]);
        Municipality::create(['name' =>'Casabianca','departament_id'=>23]);
        Municipality::create(['name' =>'Castilla la Nueva','departament_id'=>16]);
        Municipality::create(['name' =>'Caucasia','departament_id'=>1]);
        Municipality::create(['name' =>'Cañasgordas','departament_id'=>1]);
        Municipality::create(['name' =>'Cepita','departament_id'=>21]);
        Municipality::create(['name' =>'Cereté','departament_id'=>10]);
        Municipality::create(['name' =>'Cerinza','departament_id'=>5]);
        Municipality::create(['name' =>'Cerrito','departament_id'=>21]);
        Municipality::create(['name' =>'Cerro San Antonio','departament_id'=>15]);
        Municipality::create(['name' =>'Chachaguí','departament_id'=>17]);
        Municipality::create(['name' =>'Chaguaní','departament_id'=>11]);
        Municipality::create(['name' =>'Chalán','departament_id'=>22]);
        Municipality::create(['name' =>'Chaparral','departament_id'=>23]);
        Municipality::create(['name' =>'Charalá','departament_id'=>21]);
        Municipality::create(['name' =>'Charta','departament_id'=>21]);
        Municipality::create(['name' =>'Chigorodó','departament_id'=>1]);
        Municipality::create(['name' =>'Chima','departament_id'=>21]);
        Municipality::create(['name' =>'Chimichagua','departament_id'=>9]);
        Municipality::create(['name' =>'Chimá','departament_id'=>10]);
        Municipality::create(['name' =>'Chinavita','departament_id'=>5]);
        Municipality::create(['name' =>'Chinchiná','departament_id'=>6]);
        Municipality::create(['name' =>'Chinácota','departament_id'=>18]);
        Municipality::create(['name' =>'Chinú','departament_id'=>10]);
        Municipality::create(['name' =>'Chipaque','departament_id'=>11]);
        Municipality::create(['name' =>'Chipatá','departament_id'=>21]);
        Municipality::create(['name' =>'Chiquinquirá','departament_id'=>5]);
        Municipality::create(['name' =>'Chiriguaná','departament_id'=>9]);
        Municipality::create(['name' =>'Chiscas','departament_id'=>5]);
        Municipality::create(['name' =>'Chita','departament_id'=>5]);
        Municipality::create(['name' =>'Chitagá','departament_id'=>18]);
        Municipality::create(['name' =>'Chitaraque','departament_id'=>5]);
        Municipality::create(['name' =>'Chivatá','departament_id'=>5]);
        Municipality::create(['name' =>'Chivolo','departament_id'=>15]);
        Municipality::create(['name' =>'Choachí','departament_id'=>11]);
        Municipality::create(['name' =>'Chocontá','departament_id'=>11]);
        Municipality::create(['name' =>'Chámeza','departament_id'=>26]);
        Municipality::create(['name' =>'Chía','departament_id'=>11]);
        Municipality::create(['name' =>'Chíquiza','departament_id'=>5]);
        Municipality::create(['name' =>'Chívor','departament_id'=>5]);
        Municipality::create(['name' =>'Cicuco','departament_id'=>4]);
        Municipality::create(['name' =>'Cimitarra','departament_id'=>21]);
        Municipality::create(['name' =>'Circasia','departament_id'=>19]);
        Municipality::create(['name' =>'Cisneros','departament_id'=>1]);
        Municipality::create(['name' =>'Ciénaga','departament_id'=>5]);
        Municipality::create(['name' =>'Ciénaga','departament_id'=>15]);
        Municipality::create(['name' =>'Ciénaga de Oro','departament_id'=>10]);
        Municipality::create(['name' =>'Clemencia','departament_id'=>4]);
        Municipality::create(['name' =>'Cocorná','departament_id'=>1]);
        Municipality::create(['name' =>'Coello','departament_id'=>23]);
        Municipality::create(['name' =>'Cogua','departament_id'=>11]);
        Municipality::create(['name' =>'Colombia','departament_id'=>13]);
        Municipality::create(['name' =>'Colosó (Ricaurte)','departament_id'=>22]);
        Municipality::create(['name' =>'Colón','departament_id'=>27]);
        Municipality::create(['name' =>'Colón (Génova)','departament_id'=>17]);
        Municipality::create(['name' =>'Concepción','departament_id'=>1]);
        Municipality::create(['name' =>'Concepción','departament_id'=>21]);
        Municipality::create(['name' =>'Concordia','departament_id'=>1]);
        Municipality::create(['name' =>'Concordia','departament_id'=>15]);
        Municipality::create(['name' =>'Condoto','departament_id'=>12]);
        Municipality::create(['name' =>'Confines','departament_id'=>21]);
        Municipality::create(['name' =>'Consaca','departament_id'=>17]);
        Municipality::create(['name' =>'Contadero','departament_id'=>17]);
        Municipality::create(['name' =>'Contratación','departament_id'=>21]);
        Municipality::create(['name' =>'Convención','departament_id'=>18]);
        Municipality::create(['name' =>'Copacabana','departament_id'=>1]);
        Municipality::create(['name' =>'Coper','departament_id'=>5]);
        Municipality::create(['name' =>'Cordobá','departament_id'=>19]);
        Municipality::create(['name' =>'Corinto','departament_id'=>8]);
        Municipality::create(['name' =>'Coromoro','departament_id'=>21]);
        Municipality::create(['name' =>'Corozal','departament_id'=>22]);
        Municipality::create(['name' =>'Corrales','departament_id'=>5]);
        Municipality::create(['name' =>'Cota','departament_id'=>11]);
        Municipality::create(['name' =>'Cotorra','departament_id'=>10]);
        Municipality::create(['name' =>'Covarachía','departament_id'=>5]);
        Municipality::create(['name' =>'Coveñas','departament_id'=>22]);
        Municipality::create(['name' =>'Coyaima','departament_id'=>23]);
        Municipality::create(['name' =>'Cravo Norte','departament_id'=>25]);
        Municipality::create(['name' =>'Cuaspud (Carlosama)','departament_id'=>17]);
        Municipality::create(['name' =>'Cubarral','departament_id'=>16]);
        Municipality::create(['name' =>'Cubará','departament_id'=>5]);
        Municipality::create(['name' =>'Cucaita','departament_id'=>5]);
        Municipality::create(['name' =>'Cucunubá','departament_id'=>11]);
        Municipality::create(['name' =>'Cucutilla','departament_id'=>18]);
        Municipality::create(['name' =>'Cuitiva','departament_id'=>5]);
        Municipality::create(['name' =>'Cumaral','departament_id'=>16]);
        Municipality::create(['name' =>'Cumaribo','departament_id'=>33]);
        Municipality::create(['name' =>'Cumbal','departament_id'=>17]);
        Municipality::create(['name' =>'Cumbitara','departament_id'=>17]);
        Municipality::create(['name' =>'Cunday','departament_id'=>23]);
        Municipality::create(['name' =>'Curillo','departament_id'=>7]);
        Municipality::create(['name' =>'Curití','departament_id'=>21]);
        Municipality::create(['name' =>'Curumaní','departament_id'=>9]);
        Municipality::create(['name' =>'Cáceres','departament_id'=>1]);
        Municipality::create(['name' =>'Cáchira','departament_id'=>18]);
        Municipality::create(['name' =>'Cácota','departament_id'=>18]);
        Municipality::create(['name' =>'Cáqueza','departament_id'=>11]);
        Municipality::create(['name' =>'Cértegui','departament_id'=>12]);
        Municipality::create(['name' =>'Cómbita','departament_id'=>5]);
        Municipality::create(['name' =>'Córdoba','departament_id'=>4]);
        Municipality::create(['name' =>'Córdoba','departament_id'=>17]);
        Municipality::create(['name' =>'Cúcuta','departament_id'=>18]);
        Municipality::create(['name' =>'Dabeiba','departament_id'=>1]);
        Municipality::create(['name' =>'Dagua','departament_id'=>24]);
        Municipality::create(['name' =>'Dibulla','departament_id'=>14]);
        Municipality::create(['name' =>'Distracción','departament_id'=>14]);
        Municipality::create(['name' =>'Dolores','departament_id'=>23]);
        Municipality::create(['name' =>'Don Matías','departament_id'=>1]);
        Municipality::create(['name' =>'Dos Quebradas','departament_id'=>20]);
        Municipality::create(['name' =>'Duitama','departament_id'=>5]);
        Municipality::create(['name' =>'Durania','departament_id'=>18]);
        Municipality::create(['name' =>'Ebéjico','departament_id'=>1]);
        Municipality::create(['name' =>'El Bagre','departament_id'=>1]);
        Municipality::create(['name' =>'El Banco','departament_id'=>15]);
        Municipality::create(['name' =>'El Cairo','departament_id'=>24]);
        Municipality::create(['name' =>'El Calvario','departament_id'=>16]);
        Municipality::create(['name' =>'El Carmen','departament_id'=>18]);
        Municipality::create(['name' =>'El Carmen','departament_id'=>21]);
        Municipality::create(['name' =>'El Carmen de Atrato','departament_id'=>12]);
        Municipality::create(['name' =>'El Carmen de Bolívar','departament_id'=>4]);
        Municipality::create(['name' =>'El Castillo','departament_id'=>16]);
        Municipality::create(['name' =>'El Cerrito','departament_id'=>24]);
        Municipality::create(['name' =>'El Charco','departament_id'=>17]);
        Municipality::create(['name' =>'El Cocuy','departament_id'=>5]);
        Municipality::create(['name' =>'El Colegio','departament_id'=>11]);
        Municipality::create(['name' =>'El Copey','departament_id'=>9]);
        Municipality::create(['name' =>'El Doncello','departament_id'=>7]);
        Municipality::create(['name' =>'El Dorado','departament_id'=>16]);
        Municipality::create(['name' =>'El Dovio','departament_id'=>24]);
        Municipality::create(['name' =>'El Espino','departament_id'=>5]);
        Municipality::create(['name' =>'El Guacamayo','departament_id'=>21]);
        Municipality::create(['name' =>'El Guamo','departament_id'=>4]);
        Municipality::create(['name' =>'El Molino','departament_id'=>14]);
        Municipality::create(['name' =>'El Paso','departament_id'=>9]);
        Municipality::create(['name' =>'El Paujil','departament_id'=>7]);
        Municipality::create(['name' =>'El Peñol','departament_id'=>17]);
        Municipality::create(['name' =>'El Peñon','departament_id'=>4]);
        Municipality::create(['name' =>'El Peñon','departament_id'=>21]);
        Municipality::create(['name' =>'El Peñón','departament_id'=>11]);
        Municipality::create(['name' =>'El Piñon','departament_id'=>15]);
        Municipality::create(['name' =>'El Playón','departament_id'=>21]);
        Municipality::create(['name' =>'El Retorno','departament_id'=>31]);
        Municipality::create(['name' =>'El Retén','departament_id'=>15]);
        Municipality::create(['name' =>'El Roble','departament_id'=>22]);
        Municipality::create(['name' =>'El Rosal','departament_id'=>11]);
        Municipality::create(['name' =>'El Rosario','departament_id'=>17]);
        Municipality::create(['name' =>'El Tablón de Gómez','departament_id'=>17]);
        Municipality::create(['name' =>'El Tambo','departament_id'=>8]);
        Municipality::create(['name' =>'El Tambo','departament_id'=>17]);
        Municipality::create(['name' =>'El Tarra','departament_id'=>18]);
        Municipality::create(['name' =>'El Zulia','departament_id'=>18]);
        Municipality::create(['name' =>'El Águila','departament_id'=>24]);
        Municipality::create(['name' =>'Elías','departament_id'=>13]);
        Municipality::create(['name' =>'Encino','departament_id'=>21]);
        Municipality::create(['name' =>'Enciso','departament_id'=>21]);
        Municipality::create(['name' =>'Entrerríos','departament_id'=>1]);
        Municipality::create(['name' =>'Envigado','departament_id'=>1]);
        Municipality::create(['name' =>'Espinal','departament_id'=>23]);
        Municipality::create(['name' =>'Facatativá','departament_id'=>11]);
        Municipality::create(['name' =>'Falan','departament_id'=>23]);
        Municipality::create(['name' =>'Filadelfia','departament_id'=>6]);
        Municipality::create(['name' =>'Filandia','departament_id'=>19]);
        Municipality::create(['name' =>'Firavitoba','departament_id'=>5]);
        Municipality::create(['name' =>'Flandes','departament_id'=>23]);
        Municipality::create(['name' =>'Florencia','departament_id'=>7]);
        Municipality::create(['name' =>'Florencia','departament_id'=>8]);
        Municipality::create(['name' =>'Floresta','departament_id'=>5]);
        Municipality::create(['name' =>'Florida','departament_id'=>24]);
        Municipality::create(['name' =>'Floridablanca','departament_id'=>21]);
        Municipality::create(['name' =>'Florián','departament_id'=>21]);
        Municipality::create(['name' =>'Fonseca','departament_id'=>14]);
        Municipality::create(['name' =>'Fortúl','departament_id'=>25]);
        Municipality::create(['name' =>'Fosca','departament_id'=>11]);
        Municipality::create(['name' =>'Francisco Pizarro','departament_id'=>17]);
        Municipality::create(['name' =>'Fredonia','departament_id'=>1]);
        Municipality::create(['name' =>'Fresno','departament_id'=>23]);
        Municipality::create(['name' =>'Frontino','departament_id'=>1]);
        Municipality::create(['name' =>'Fuente de Oro','departament_id'=>16]);
        Municipality::create(['name' =>'Fundación','departament_id'=>15]);
        Municipality::create(['name' =>'Funes','departament_id'=>17]);
        Municipality::create(['name' =>'Funza','departament_id'=>11]);
        Municipality::create(['name' =>'Fusagasugá','departament_id'=>11]);
        Municipality::create(['name' =>'Fómeque','departament_id'=>11]);
        Municipality::create(['name' =>'Fúquene','departament_id'=>11]);
        Municipality::create(['name' =>'Gachalá','departament_id'=>11]);
        Municipality::create(['name' =>'Gachancipá','departament_id'=>11]);
        Municipality::create(['name' =>'Gachantivá','departament_id'=>5]);
        Municipality::create(['name' =>'Gachetá','departament_id'=>11]);
        Municipality::create(['name' =>'Galapa','departament_id'=>2]);
        Municipality::create(['name' =>'Galeras (Nueva Granada)','departament_id'=>22]);
        Municipality::create(['name' =>'Galán','departament_id'=>21]);
        Municipality::create(['name' =>'Gama','departament_id'=>11]);
        Municipality::create(['name' =>'Gamarra','departament_id'=>9]);
        Municipality::create(['name' =>'Garagoa','departament_id'=>5]);
        Municipality::create(['name' =>'Garzón','departament_id'=>13]);
        Municipality::create(['name' =>'Gigante','departament_id'=>13]);
        Municipality::create(['name' =>'Ginebra','departament_id'=>24]);
        Municipality::create(['name' =>'Giraldo','departament_id'=>1]);
        Municipality::create(['name' =>'Girardot','departament_id'=>11]);
        Municipality::create(['name' =>'Girardota','departament_id'=>1]);
        Municipality::create(['name' =>'Girón','departament_id'=>21]);
        Municipality::create(['name' =>'Gonzalez','departament_id'=>9]);
        Municipality::create(['name' =>'Gramalote','departament_id'=>18]);
        Municipality::create(['name' =>'Granada','departament_id'=>1]);
        Municipality::create(['name' =>'Granada','departament_id'=>11]);
        Municipality::create(['name' =>'Granada','departament_id'=>16]);
        Municipality::create(['name' =>'Guaca','departament_id'=>21]);
        Municipality::create(['name' =>'Guacamayas','departament_id'=>5]);
        Municipality::create(['name' =>'Guacarí','departament_id'=>24]);
        Municipality::create(['name' =>'Guachavés','departament_id'=>17]);
        Municipality::create(['name' =>'Guachené','departament_id'=>8]);
        Municipality::create(['name' =>'Guachetá','departament_id'=>11]);
        Municipality::create(['name' =>'Guachucal','departament_id'=>17]);
        Municipality::create(['name' =>'Guadalupe','departament_id'=>1]);
        Municipality::create(['name' =>'Guadalupe','departament_id'=>13]);
        Municipality::create(['name' =>'Guadalupe','departament_id'=>21]);
        Municipality::create(['name' =>'Guaduas','departament_id'=>11]);
        Municipality::create(['name' =>'Guaitarilla','departament_id'=>17]);
        Municipality::create(['name' =>'Gualmatán','departament_id'=>17]);
        Municipality::create(['name' =>'Guamal','departament_id'=>15]);
        Municipality::create(['name' =>'Guamal','departament_id'=>16]);
        Municipality::create(['name' =>'Guamo','departament_id'=>23]);
        Municipality::create(['name' =>'Guapota','departament_id'=>21]);
        Municipality::create(['name' =>'Guapí','departament_id'=>8]);
        Municipality::create(['name' =>'Guaranda','departament_id'=>22]);
        Municipality::create(['name' =>'Guarne','departament_id'=>1]);
        Municipality::create(['name' =>'Guasca','departament_id'=>11]);
        Municipality::create(['name' =>'Guatapé','departament_id'=>1]);
        Municipality::create(['name' =>'Guataquí','departament_id'=>11]);
        Municipality::create(['name' =>'Guatavita','departament_id'=>11]);
        Municipality::create(['name' =>'Guateque','departament_id'=>5]);
        Municipality::create(['name' =>'Guavatá','departament_id'=>21]);
        Municipality::create(['name' =>'Guayabal de Siquima','departament_id'=>11]);
        Municipality::create(['name' =>'Guayabetal','departament_id'=>11]);
        Municipality::create(['name' =>'Guayatá','departament_id'=>5]);
        Municipality::create(['name' =>'Guepsa','departament_id'=>21]);
        Municipality::create(['name' =>'Guicán','departament_id'=>5]);
        Municipality::create(['name' =>'Gutiérrez','departament_id'=>11]);
        Municipality::create(['name' =>'Guática','departament_id'=>20]);
        Municipality::create(['name' =>'Gámbita','departament_id'=>21]);
        Municipality::create(['name' =>'Gámeza','departament_id'=>5]);
        Municipality::create(['name' =>'Génova','departament_id'=>19]);
        Municipality::create(['name' =>'Gómez Plata','departament_id'=>1]);
        Municipality::create(['name' =>'Hacarí','departament_id'=>18]);
        Municipality::create(['name' =>'Hatillo de Loba','departament_id'=>4]);
        Municipality::create(['name' =>'Hato','departament_id'=>21]);
        Municipality::create(['name' =>'Hato Corozal','departament_id'=>26]);
        Municipality::create(['name' =>'Hatonuevo','departament_id'=>14]);
        Municipality::create(['name' =>'Heliconia','departament_id'=>1]);
        Municipality::create(['name' =>'Herrán','departament_id'=>18]);
        Municipality::create(['name' =>'Herveo','departament_id'=>23]);
        Municipality::create(['name' =>'Hispania','departament_id'=>1]);
        Municipality::create(['name' =>'Hobo','departament_id'=>13]);
        Municipality::create(['name' =>'Honda','departament_id'=>23]);
        Municipality::create(['name' =>'Ibagué','departament_id'=>23]);
        Municipality::create(['name' =>'Icononzo','departament_id'=>23]);
        Municipality::create(['name' =>'Iles','departament_id'=>17]);
        Municipality::create(['name' =>'Imúes','departament_id'=>17]);
        Municipality::create(['name' =>'Inzá','departament_id'=>8]);
        Municipality::create(['name' =>'Inírida','departament_id'=>30]);
        Municipality::create(['name' =>'Ipiales','departament_id'=>17]);
        Municipality::create(['name' =>'Isnos','departament_id'=>13]);
        Municipality::create(['name' =>'Istmina','departament_id'=>12]);
        Municipality::create(['name' =>'Itagüí','departament_id'=>1]);
        Municipality::create(['name' =>'Ituango','departament_id'=>1]);
        Municipality::create(['name' =>'Izá','departament_id'=>5]);
        Municipality::create(['name' =>'Jambaló','departament_id'=>8]);
        Municipality::create(['name' =>'Jamundí','departament_id'=>24]);
        Municipality::create(['name' =>'Jardín','departament_id'=>1]);
        Municipality::create(['name' =>'Jenesano','departament_id'=>5]);
        Municipality::create(['name' =>'Jericó','departament_id'=>1]);
        Municipality::create(['name' =>'Jericó','departament_id'=>5]);
        Municipality::create(['name' =>'Jerusalén','departament_id'=>11]);
        Municipality::create(['name' =>'Jesús María','departament_id'=>21]);
        Municipality::create(['name' =>'Jordán','departament_id'=>21]);
        Municipality::create(['name' =>'Juan de Acosta','departament_id'=>2]);
        Municipality::create(['name' =>'Junín','departament_id'=>11]);
        Municipality::create(['name' =>'Juradó','departament_id'=>12]);
        Municipality::create(['name' =>'La Apartada y La Frontera','departament_id'=>10]);
        Municipality::create(['name' =>'La Argentina','departament_id'=>13]);
        Municipality::create(['name' =>'La Belleza','departament_id'=>21]);
        Municipality::create(['name' =>'La Calera','departament_id'=>11]);
        Municipality::create(['name' =>'La Capilla','departament_id'=>5]);
        Municipality::create(['name' =>'La Ceja','departament_id'=>1]);
        Municipality::create(['name' =>'La Celia','departament_id'=>20]);
        Municipality::create(['name' =>'La Cruz','departament_id'=>17]);
        Municipality::create(['name' =>'La Cumbre','departament_id'=>24]);
        Municipality::create(['name' =>'La Dorada','departament_id'=>6]);
        Municipality::create(['name' =>'La Esperanza','departament_id'=>18]);
        Municipality::create(['name' =>'La Estrella','departament_id'=>1]);
        Municipality::create(['name' =>'La Florida','departament_id'=>17]);
        Municipality::create(['name' =>'La Gloria','departament_id'=>9]);
        Municipality::create(['name' =>'La Jagua de Ibirico','departament_id'=>9]);
        Municipality::create(['name' =>'La Jagua del Pilar','departament_id'=>14]);
        Municipality::create(['name' =>'La Llanada','departament_id'=>17]);
        Municipality::create(['name' =>'La Macarena','departament_id'=>16]);
        Municipality::create(['name' =>'La Merced','departament_id'=>6]);
        Municipality::create(['name' =>'La Mesa','departament_id'=>11]);
        Municipality::create(['name' =>'La Montañita','departament_id'=>7]);
        Municipality::create(['name' =>'La Palma','departament_id'=>11]);
        Municipality::create(['name' =>'La Paz','departament_id'=>21]);
        Municipality::create(['name' =>'La Paz (Robles)','departament_id'=>9]);
        Municipality::create(['name' =>'La Peña','departament_id'=>11]);
        Municipality::create(['name' =>'La Pintada','departament_id'=>1]);
        Municipality::create(['name' =>'La Plata','departament_id'=>13]);
        Municipality::create(['name' =>'La Playa','departament_id'=>18]);
        Municipality::create(['name' =>'La Primavera','departament_id'=>33]);
        Municipality::create(['name' =>'La Salina','departament_id'=>26]);
        Municipality::create(['name' =>'La Sierra','departament_id'=>8]);
        Municipality::create(['name' =>'La Tebaida','departament_id'=>19]);
        Municipality::create(['name' =>'La Tola','departament_id'=>17]);
        Municipality::create(['name' =>'La Unión','departament_id'=>1]);
        Municipality::create(['name' =>'La Unión','departament_id'=>17]);
        Municipality::create(['name' =>'La Unión','departament_id'=>22]);
        Municipality::create(['name' =>'La Unión','departament_id'=>24]);
        Municipality::create(['name' =>'La Uvita','departament_id'=>5]);
        Municipality::create(['name' =>'La Vega','departament_id'=>8]);
        Municipality::create(['name' =>'La Vega','departament_id'=>11]);
        Municipality::create(['name' =>'La Victoria','departament_id'=>5]);
        Municipality::create(['name' =>'La Victoria','departament_id'=>6]);
        Municipality::create(['name' =>'La Victoria','departament_id'=>24]);
        Municipality::create(['name' =>'La Virginia','departament_id'=>20]);
        Municipality::create(['name' =>'Labateca','departament_id'=>18]);
        Municipality::create(['name' =>'Labranzagrande','departament_id'=>5]);
        Municipality::create(['name' =>'Landázuri','departament_id'=>21]);
        Municipality::create(['name' =>'Lebrija','departament_id'=>21]);
        Municipality::create(['name' =>'Leiva','departament_id'=>17]);
        Municipality::create(['name' =>'Lejanías','departament_id'=>16]);
        Municipality::create(['name' =>'Lenguazaque','departament_id'=>11]);
        Municipality::create(['name' =>'Leticia','departament_id'=>29]);
        Municipality::create(['name' =>'Liborina','departament_id'=>1]);
        Municipality::create(['name' =>'Linares','departament_id'=>17]);
        Municipality::create(['name' =>'Lloró','departament_id'=>12]);
        Municipality::create(['name' =>'Lorica','departament_id'=>10]);
        Municipality::create(['name' =>'Los Córdobas','departament_id'=>10]);
        Municipality::create(['name' =>'Los Palmitos','departament_id'=>22]);
        Municipality::create(['name' =>'Los Patios','departament_id'=>18]);
        Municipality::create(['name' =>'Los Santos','departament_id'=>21]);
        Municipality::create(['name' =>'Lourdes','departament_id'=>18]);
        Municipality::create(['name' =>'Luruaco','departament_id'=>2]);
        Municipality::create(['name' =>'Lérida','departament_id'=>23]);
        Municipality::create(['name' =>'Líbano','departament_id'=>23]);
        Municipality::create(['name' =>'López (Micay)','departament_id'=>8]);
        Municipality::create(['name' =>'Macanal','departament_id'=>5]);
        Municipality::create(['name' =>'Macaravita','departament_id'=>21]);
        Municipality::create(['name' =>'Maceo','departament_id'=>1]);
        Municipality::create(['name' =>'Machetá','departament_id'=>11]);
        Municipality::create(['name' =>'Madrid','departament_id'=>11]);
        Municipality::create(['name' =>'Magangué','departament_id'=>4]);
        Municipality::create(['name' =>'Magüi (Payán)','departament_id'=>17]);
        Municipality::create(['name' =>'Mahates','departament_id'=>4]);
        Municipality::create(['name' =>'Maicao','departament_id'=>14]);
        Municipality::create(['name' =>'Majagual','departament_id'=>22]);
        Municipality::create(['name' =>'Malambo','departament_id'=>2]);
        Municipality::create(['name' =>'Mallama (Piedrancha)','departament_id'=>17]);
        Municipality::create(['name' =>'Manatí','departament_id'=>2]);
        Municipality::create(['name' =>'Manaure','departament_id'=>14]);
        Municipality::create(['name' =>'Manaure Balcón del Cesar','departament_id'=>9]);
        Municipality::create(['name' =>'Manizales','departament_id'=>6]);
        Municipality::create(['name' =>'Manta','departament_id'=>11]);
        Municipality::create(['name' =>'Manzanares','departament_id'=>6]);
        Municipality::create(['name' =>'Maní','departament_id'=>26]);
        Municipality::create(['name' =>'Mapiripan','departament_id'=>16]);
        Municipality::create(['name' =>'Margarita','departament_id'=>4]);
        Municipality::create(['name' =>'Marinilla','departament_id'=>1]);
        Municipality::create(['name' =>'Maripí','departament_id'=>5]);
        Municipality::create(['name' =>'Mariquita','departament_id'=>23]);
        Municipality::create(['name' =>'Marmato','departament_id'=>6]);
        Municipality::create(['name' =>'Marquetalia','departament_id'=>6]);
        Municipality::create(['name' =>'Marsella','departament_id'=>20]);
        Municipality::create(['name' =>'Marulanda','departament_id'=>6]);
        Municipality::create(['name' =>'María la Baja','departament_id'=>4]);
        Municipality::create(['name' =>'Matanza','departament_id'=>21]);
        Municipality::create(['name' =>'Medellín','departament_id'=>1]);
        Municipality::create(['name' =>'Medina','departament_id'=>11]);
        Municipality::create(['name' =>'Medio Atrato','departament_id'=>12]);
        Municipality::create(['name' =>'Medio Baudó','departament_id'=>12]);
        Municipality::create(['name' =>'Medio San Juan (ANDAGOYA)','departament_id'=>12]);
        Municipality::create(['name' =>'Melgar','departament_id'=>23]);
        Municipality::create(['name' =>'Mercaderes','departament_id'=>8]);
        Municipality::create(['name' =>'Mesetas','departament_id'=>16]);
        Municipality::create(['name' =>'Milán','departament_id'=>7]);
        Municipality::create(['name' =>'Miraflores','departament_id'=>5]);
        Municipality::create(['name' =>'Miraflores','departament_id'=>31]);
        Municipality::create(['name' =>'Miranda','departament_id'=>8]);
        Municipality::create(['name' =>'Mistrató','departament_id'=>20]);
        Municipality::create(['name' =>'Mitú','departament_id'=>32]);
        Municipality::create(['name' =>'Mocoa','departament_id'=>27]);
        Municipality::create(['name' =>'Mogotes','departament_id'=>21]);
        Municipality::create(['name' =>'Molagavita','departament_id'=>21]);
        Municipality::create(['name' =>'Momil','departament_id'=>10]);
        Municipality::create(['name' =>'Mompós','departament_id'=>4]);
        Municipality::create(['name' =>'Mongua','departament_id'=>5]);
        Municipality::create(['name' =>'Monguí','departament_id'=>5]);
        Municipality::create(['name' =>'Moniquirá','departament_id'=>5]);
        Municipality::create(['name' =>'Montebello','departament_id'=>1]);
        Municipality::create(['name' =>'Montecristo','departament_id'=>4]);
        Municipality::create(['name' =>'Montelíbano','departament_id'=>10]);
        Municipality::create(['name' =>'Montenegro','departament_id'=>19]);
        Municipality::create(['name' =>'Monteria','departament_id'=>10]);
        Municipality::create(['name' =>'Monterrey','departament_id'=>26]);
        Municipality::create(['name' =>'Morales','departament_id'=>4]);
        Municipality::create(['name' =>'Morales','departament_id'=>8]);
        Municipality::create(['name' =>'Morelia','departament_id'=>7]);
        Municipality::create(['name' =>'Morroa','departament_id'=>22]);
        Municipality::create(['name' =>'Mosquera','departament_id'=>11]);
        Municipality::create(['name' =>'Mosquera','departament_id'=>17]);
        Municipality::create(['name' =>'Motavita','departament_id'=>5]);
        Municipality::create(['name' =>'Moñitos','departament_id'=>10]);
        Municipality::create(['name' =>'Murillo','departament_id'=>23]);
        Municipality::create(['name' =>'Murindó','departament_id'=>1]);
        Municipality::create(['name' =>'Mutatá','departament_id'=>1]);
        Municipality::create(['name' =>'Mutiscua','departament_id'=>18]);
        Municipality::create(['name' =>'Muzo','departament_id'=>5]);
        Municipality::create(['name' =>'Málaga','departament_id'=>21]);
        Municipality::create(['name' =>'Nariño','departament_id'=>1]);
        Municipality::create(['name' =>'Nariño','departament_id'=>11]);
        Municipality::create(['name' =>'Nariño','departament_id'=>17]);
        Municipality::create(['name' =>'Natagaima','departament_id'=>23]);
        Municipality::create(['name' =>'Nechí','departament_id'=>1]);
        Municipality::create(['name' =>'Necoclí','departament_id'=>1]);
        Municipality::create(['name' =>'Neira','departament_id'=>6]);
        Municipality::create(['name' =>'Neiva','departament_id'=>13]);
        Municipality::create(['name' =>'Nemocón','departament_id'=>11]);
        Municipality::create(['name' =>'Nilo','departament_id'=>11]);
        Municipality::create(['name' =>'Nimaima','departament_id'=>11]);
        Municipality::create(['name' =>'Nobsa','departament_id'=>5]);
        Municipality::create(['name' =>'Nocaima','departament_id'=>11]);
        Municipality::create(['name' =>'Norcasia','departament_id'=>6]);
        Municipality::create(['name' =>'Norosí','departament_id'=>4]);
        Municipality::create(['name' =>'Novita','departament_id'=>12]);
        Municipality::create(['name' =>'Nueva Granada','departament_id'=>15]);
        Municipality::create(['name' =>'Nuevo Colón','departament_id'=>5]);
        Municipality::create(['name' =>'Nunchía','departament_id'=>26]);
        Municipality::create(['name' =>'Nuquí','departament_id'=>12]);
        Municipality::create(['name' =>'Nátaga','departament_id'=>13]);
        Municipality::create(['name' =>'Obando','departament_id'=>24]);
        Municipality::create(['name' =>'Ocamonte','departament_id'=>21]);
        Municipality::create(['name' =>'Ocaña','departament_id'=>18]);
        Municipality::create(['name' =>'Oiba','departament_id'=>21]);
        Municipality::create(['name' =>'Oicatá','departament_id'=>5]);
        Municipality::create(['name' =>'Olaya','departament_id'=>1]);
        Municipality::create(['name' =>'Olaya Herrera','departament_id'=>17]);
        Municipality::create(['name' =>'Onzaga','departament_id'=>21]);
        Municipality::create(['name' =>'Oporapa','departament_id'=>13]);
        Municipality::create(['name' =>'Orito','departament_id'=>27]);
        Municipality::create(['name' =>'Orocué','departament_id'=>26]);
        Municipality::create(['name' =>'Ortega','departament_id'=>23]);
        Municipality::create(['name' =>'Ospina','departament_id'=>17]);
        Municipality::create(['name' =>'Otanche','departament_id'=>5]);
        Municipality::create(['name' =>'Ovejas','departament_id'=>22]);
        Municipality::create(['name' =>'Pachavita','departament_id'=>5]);
        Municipality::create(['name' =>'Pacho','departament_id'=>11]);
        Municipality::create(['name' =>'Padilla','departament_id'=>8]);
        Municipality::create(['name' =>'Paicol','departament_id'=>13]);
        Municipality::create(['name' =>'Pailitas','departament_id'=>9]);
        Municipality::create(['name' =>'Paime','departament_id'=>11]);
        Municipality::create(['name' =>'Paipa','departament_id'=>5]);
        Municipality::create(['name' =>'Pajarito','departament_id'=>5]);
        Municipality::create(['name' =>'Palermo','departament_id'=>13]);
        Municipality::create(['name' =>'Palestina','departament_id'=>6]);
        Municipality::create(['name' =>'Palestina','departament_id'=>13]);
        Municipality::create(['name' =>'Palmar','departament_id'=>21]);
        Municipality::create(['name' =>'Palmar de Varela','departament_id'=>2]);
        Municipality::create(['name' =>'Palmas del Socorro','departament_id'=>21]);
        Municipality::create(['name' =>'Palmira','departament_id'=>24]);
        Municipality::create(['name' =>'Palmito','departament_id'=>22]);
        Municipality::create(['name' =>'Palocabildo','departament_id'=>23]);
        Municipality::create(['name' =>'Pamplona','departament_id'=>18]);
        Municipality::create(['name' =>'Pamplonita','departament_id'=>18]);
        Municipality::create(['name' =>'Pandi','departament_id'=>11]);
        Municipality::create(['name' =>'Panqueba','departament_id'=>5]);
        Municipality::create(['name' =>'Paratebueno','departament_id'=>11]);
        Municipality::create(['name' =>'Pasca','departament_id'=>11]);
        Municipality::create(['name' =>'Patía (El Bordo)','departament_id'=>8]);
        Municipality::create(['name' =>'Pauna','departament_id'=>5]);
        Municipality::create(['name' =>'Paya','departament_id'=>5]);
        Municipality::create(['name' =>'Paz de Ariporo','departament_id'=>26]);
        Municipality::create(['name' =>'Paz de Río','departament_id'=>5]);
        Municipality::create(['name' =>'Pedraza','departament_id'=>15]);
        Municipality::create(['name' =>'Pelaya','departament_id'=>9]);
        Municipality::create(['name' =>'Pensilvania','departament_id'=>6]);
        Municipality::create(['name' =>'Peque','departament_id'=>1]);
        Municipality::create(['name' =>'Pereira','departament_id'=>20]);
        Municipality::create(['name' =>'Pesca','departament_id'=>5]);
        Municipality::create(['name' =>'Peñol','departament_id'=>1]);
        Municipality::create(['name' =>'Piamonte','departament_id'=>8]);
        Municipality::create(['name' =>'Pie de Cuesta','departament_id'=>21]);
        Municipality::create(['name' =>'Piedras','departament_id'=>23]);
        Municipality::create(['name' =>'Piendamó','departament_id'=>8]);
        Municipality::create(['name' =>'Pijao','departament_id'=>19]);
        Municipality::create(['name' =>'Pijiño','departament_id'=>15]);
        Municipality::create(['name' =>'Pinchote','departament_id'=>21]);
        Municipality::create(['name' =>'Pinillos','departament_id'=>4]);
        Municipality::create(['name' =>'Piojo','departament_id'=>2]);
        Municipality::create(['name' =>'Pisva','departament_id'=>5]);
        Municipality::create(['name' =>'Pital','departament_id'=>13]);
        Municipality::create(['name' =>'Pitalito','departament_id'=>13]);
        Municipality::create(['name' =>'Pivijay','departament_id'=>15]);
        Municipality::create(['name' =>'Planadas','departament_id'=>23]);
        Municipality::create(['name' =>'Planeta Rica','departament_id'=>10]);
        Municipality::create(['name' =>'Plato','departament_id'=>15]);
        Municipality::create(['name' =>'Policarpa','departament_id'=>17]);
        Municipality::create(['name' =>'Polonuevo','departament_id'=>2]);
        Municipality::create(['name' =>'Ponedera','departament_id'=>2]);
        Municipality::create(['name' =>'Popayán','departament_id'=>8]);
        Municipality::create(['name' =>'Pore','departament_id'=>26]);
        Municipality::create(['name' =>'Potosí','departament_id'=>17]);
        Municipality::create(['name' =>'Pradera','departament_id'=>24]);
        Municipality::create(['name' =>'Prado','departament_id'=>23]);
        Municipality::create(['name' =>'Providencia','departament_id'=>17]);
        Municipality::create(['name' =>'Providencia','departament_id'=>28]);
        Municipality::create(['name' =>'Pueblo Bello','departament_id'=>9]);
        Municipality::create(['name' =>'Pueblo Nuevo','departament_id'=>10]);
        Municipality::create(['name' =>'Pueblo Rico','departament_id'=>20]);
        Municipality::create(['name' =>'Pueblorrico','departament_id'=>1]);
        Municipality::create(['name' =>'Puebloviejo','departament_id'=>15]);
        Municipality::create(['name' =>'Puente Nacional','departament_id'=>21]);
        Municipality::create(['name' =>'Puerres','departament_id'=>17]);
        Municipality::create(['name' =>'Puerto Asís','departament_id'=>27]);
        Municipality::create(['name' =>'Puerto Berrío','departament_id'=>1]);
        Municipality::create(['name' =>'Puerto Boyacá','departament_id'=>5]);
        Municipality::create(['name' =>'Puerto Caicedo','departament_id'=>27]);
        Municipality::create(['name' =>'Puerto Carreño','departament_id'=>33]);
        Municipality::create(['name' =>'Puerto Colombia','departament_id'=>2]);
        Municipality::create(['name' =>'Puerto Concordia','departament_id'=>16]);
        Municipality::create(['name' =>'Puerto Escondido','departament_id'=>10]);
        Municipality::create(['name' =>'Puerto Gaitán','departament_id'=>16]);
        Municipality::create(['name' =>'Puerto Guzmán','departament_id'=>27]);
        Municipality::create(['name' =>'Puerto Leguízamo','departament_id'=>27]);
        Municipality::create(['name' =>'Puerto Libertador','departament_id'=>10]);
        Municipality::create(['name' =>'Puerto Lleras','departament_id'=>16]);
        Municipality::create(['name' =>'Puerto López','departament_id'=>16]);
        Municipality::create(['name' =>'Puerto Nare','departament_id'=>1]);
        Municipality::create(['name' =>'Puerto Nariño','departament_id'=>29]);
        Municipality::create(['name' =>'Puerto Parra','departament_id'=>21]);
        Municipality::create(['name' =>'Puerto Rico','departament_id'=>7]);
        Municipality::create(['name' =>'Puerto Rico','departament_id'=>16]);
        Municipality::create(['name' =>'Puerto Rondón','departament_id'=>25]);
        Municipality::create(['name' =>'Puerto Salgar','departament_id'=>11]);
        Municipality::create(['name' =>'Puerto Santander','departament_id'=>18]);
        Municipality::create(['name' =>'Puerto Tejada','departament_id'=>8]);
        Municipality::create(['name' =>'Puerto Triunfo','departament_id'=>1]);
        Municipality::create(['name' =>'Puerto Wilches','departament_id'=>21]);
        Municipality::create(['name' =>'Pulí','departament_id'=>11]);
        Municipality::create(['name' =>'Pupiales','departament_id'=>17]);
        Municipality::create(['name' =>'Puracé (Coconuco)','departament_id'=>8]);
        Municipality::create(['name' =>'Purificación','departament_id'=>23]);
        Municipality::create(['name' =>'Purísima','departament_id'=>10]);
        Municipality::create(['name' =>'Pácora','departament_id'=>6]);
        Municipality::create(['name' =>'Páez','departament_id'=>5]);
        Municipality::create(['name' =>'Páez (Belalcazar)','departament_id'=>8]);
        Municipality::create(['name' =>'Páramo','departament_id'=>21]);
        Municipality::create(['name' =>'Quebradanegra','departament_id'=>11]);
        Municipality::create(['name' =>'Quetame','departament_id'=>11]);
        Municipality::create(['name' =>'Quibdó','departament_id'=>12]);
        Municipality::create(['name' =>'Quimbaya','departament_id'=>19]);
        Municipality::create(['name' =>'Quinchía','departament_id'=>20]);
        Municipality::create(['name' =>'Quipama','departament_id'=>5]);
        Municipality::create(['name' =>'Quipile','departament_id'=>11]);
        Municipality::create(['name' =>'Ragonvalia','departament_id'=>18]);
        Municipality::create(['name' =>'Ramiriquí','departament_id'=>5]);
        Municipality::create(['name' =>'Recetor','departament_id'=>26]);
        Municipality::create(['name' =>'Regidor','departament_id'=>4]);
        Municipality::create(['name' =>'Remedios','departament_id'=>1]);
        Municipality::create(['name' =>'Remolino','departament_id'=>15]);
        Municipality::create(['name' =>'Repelón','departament_id'=>2]);
        Municipality::create(['name' =>'Restrepo','departament_id'=>16]);
        Municipality::create(['name' =>'Restrepo','departament_id'=>24]);
        Municipality::create(['name' =>'Retiro','departament_id'=>1]);
        Municipality::create(['name' =>'Ricaurte','departament_id'=>11]);
        Municipality::create(['name' =>'Ricaurte','departament_id'=>17]);
        Municipality::create(['name' =>'Rio Negro','departament_id'=>21]);
        Municipality::create(['name' =>'Rioblanco','departament_id'=>23]);
        Municipality::create(['name' =>'Riofrío','departament_id'=>24]);
        Municipality::create(['name' =>'Riohacha','departament_id'=>14]);
        Municipality::create(['name' =>'Risaralda','departament_id'=>6]);
        Municipality::create(['name' =>'Rivera','departament_id'=>13]);
        Municipality::create(['name' =>'Roberto Payán (San José)','departament_id'=>17]);
        Municipality::create(['name' =>'Roldanillo','departament_id'=>24]);
        Municipality::create(['name' =>'Roncesvalles','departament_id'=>23]);
        Municipality::create(['name' =>'Rondón','departament_id'=>5]);
        Municipality::create(['name' =>'Rosas','departament_id'=>8]);
        Municipality::create(['name' =>'Rovira','departament_id'=>23]);
        Municipality::create(['name' =>'Ráquira','departament_id'=>5]);
        Municipality::create(['name' =>'Río Iró','departament_id'=>12]);
        Municipality::create(['name' =>'Río Quito','departament_id'=>12]);
        Municipality::create(['name' =>'Río Sucio','departament_id'=>6]);
        Municipality::create(['name' =>'Río Viejo','departament_id'=>4]);
        Municipality::create(['name' =>'Río de oro','departament_id'=>9]);
        Municipality::create(['name' =>'Ríonegro','departament_id'=>1]);
        Municipality::create(['name' =>'Ríosucio','departament_id'=>12]);
        Municipality::create(['name' =>'Sabana de Torres','departament_id'=>21]);
        Municipality::create(['name' =>'Sabanagrande','departament_id'=>2]);
        Municipality::create(['name' =>'Sabanalarga','departament_id'=>1]);
        Municipality::create(['name' =>'Sabanalarga','departament_id'=>2]);
        Municipality::create(['name' =>'Sabanalarga','departament_id'=>26]);
        Municipality::create(['name' =>'Sabanas de San Angel (SAN ANGEL)','departament_id'=>15]);
        Municipality::create(['name' =>'Sabaneta','departament_id'=>1]);
        Municipality::create(['name' =>'Saboyá','departament_id'=>5]);
        Municipality::create(['name' =>'Sahagún','departament_id'=>10]);
        Municipality::create(['name' =>'Saladoblanco','departament_id'=>13]);
        Municipality::create(['name' =>'Salamina','departament_id'=>6]);
        Municipality::create(['name' =>'Salamina','departament_id'=>15]);
        Municipality::create(['name' =>'Salazar','departament_id'=>18]);
        Municipality::create(['name' =>'Saldaña','departament_id'=>23]);
        Municipality::create(['name' =>'Salento','departament_id'=>19]);
        Municipality::create(['name' =>'Salgar','departament_id'=>1]);
        Municipality::create(['name' =>'Samacá','departament_id'=>5]);
        Municipality::create(['name' =>'Samaniego','departament_id'=>17]);
        Municipality::create(['name' =>'Samaná','departament_id'=>6]);
        Municipality::create(['name' =>'Sampués','departament_id'=>22]);
        Municipality::create(['name' =>'San Agustín','departament_id'=>13]);
        Municipality::create(['name' =>'San Alberto','departament_id'=>9]);
        Municipality::create(['name' =>'San Andrés','departament_id'=>28]);
        Municipality::create(['name' =>'San Andrés Sotavento','departament_id'=>10]);
        Municipality::create(['name' =>'San Andrés de Cuerquía','departament_id'=>1]);
        Municipality::create(['name' =>'San Antero','departament_id'=>10]);
        Municipality::create(['name' =>'San Antonio','departament_id'=>23]);
        Municipality::create(['name' =>'San Antonio de Tequendama','departament_id'=>11]);
        Municipality::create(['name' =>'San Benito','departament_id'=>21]);
        Municipality::create(['name' =>'San Benito Abad','departament_id'=>22]);
        Municipality::create(['name' =>'San Bernardo','departament_id'=>11]);
        Municipality::create(['name' =>'San Bernardo','departament_id'=>17]);
        Municipality::create(['name' =>'San Bernardo del Viento','departament_id'=>10]);
        Municipality::create(['name' =>'San Calixto','departament_id'=>18]);
        Municipality::create(['name' =>'San Carlos','departament_id'=>1]);
        Municipality::create(['name' =>'San Carlos','departament_id'=>10]);
        Municipality::create(['name' =>'San Carlos de Guaroa','departament_id'=>16]);
        Municipality::create(['name' =>'San Cayetano','departament_id'=>11]);
        Municipality::create(['name' =>'San Cayetano','departament_id'=>18]);
        Municipality::create(['name' =>'San Cristobal','departament_id'=>4]);
        Municipality::create(['name' =>'San Diego','departament_id'=>9]);
        Municipality::create(['name' =>'San Eduardo','departament_id'=>5]);
        Municipality::create(['name' =>'San Estanislao','departament_id'=>4]);
        Municipality::create(['name' =>'San Fernando','departament_id'=>4]);
        Municipality::create(['name' =>'San Francisco','departament_id'=>1]);
        Municipality::create(['name' =>'San Francisco','departament_id'=>11]);
        Municipality::create(['name' =>'San Francisco','departament_id'=>27]);
        Municipality::create(['name' =>'San Gíl','departament_id'=>21]);
        Municipality::create(['name' =>'San Jacinto','departament_id'=>4]);
        Municipality::create(['name' =>'San Jacinto del Cauca','departament_id'=>4]);
        Municipality::create(['name' =>'San Jerónimo','departament_id'=>1]);
        Municipality::create(['name' =>'San Joaquín','departament_id'=>21]);
        Municipality::create(['name' =>'San José','departament_id'=>6]);
        Municipality::create(['name' =>'San José de Miranda','departament_id'=>21]);
        Municipality::create(['name' =>'San José de Montaña','departament_id'=>1]);
        Municipality::create(['name' =>'San José de Pare','departament_id'=>5]);
        Municipality::create(['name' =>'San José de Uré','departament_id'=>10]);
        Municipality::create(['name' =>'San José del Fragua','departament_id'=>7]);
        Municipality::create(['name' =>'San José del Guaviare','departament_id'=>31]);
        Municipality::create(['name' =>'San José del Palmar','departament_id'=>12]);
        Municipality::create(['name' =>'San Juan de Arama','departament_id'=>16]);
        Municipality::create(['name' =>'San Juan de Betulia','departament_id'=>22]);
        Municipality::create(['name' =>'San Juan de Nepomuceno','departament_id'=>4]);
        Municipality::create(['name' =>'San Juan de Pasto','departament_id'=>17]);
        Municipality::create(['name' =>'San Juan de Río Seco','departament_id'=>11]);
        Municipality::create(['name' =>'San Juan de Urabá','departament_id'=>1]);
        Municipality::create(['name' =>'San Juan del Cesar','departament_id'=>14]);
        Municipality::create(['name' =>'San Juanito','departament_id'=>16]);
        Municipality::create(['name' =>'San Lorenzo','departament_id'=>17]);
        Municipality::create(['name' =>'San Luis','departament_id'=>23]);
        Municipality::create(['name' =>'San Luís','departament_id'=>1]);
        Municipality::create(['name' =>'San Luís de Gaceno','departament_id'=>5]);
        Municipality::create(['name' =>'San Luís de Palenque','departament_id'=>26]);
        Municipality::create(['name' =>'San Marcos','departament_id'=>22]);
        Municipality::create(['name' =>'San Martín','departament_id'=>9]);
        Municipality::create(['name' =>'San Martín','departament_id'=>16]);
        Municipality::create(['name' =>'San Martín de Loba','departament_id'=>4]);
        Municipality::create(['name' =>'San Mateo','departament_id'=>5]);
        Municipality::create(['name' =>'San Miguel','departament_id'=>21]);
        Municipality::create(['name' =>'San Miguel','departament_id'=>27]);
        Municipality::create(['name' =>'San Miguel de Sema','departament_id'=>5]);
        Municipality::create(['name' =>'San Onofre','departament_id'=>22]);
        Municipality::create(['name' =>'San Pablo','departament_id'=>4]);
        Municipality::create(['name' =>'San Pablo','departament_id'=>17]);
        Municipality::create(['name' =>'San Pablo de Borbur','departament_id'=>5]);
        Municipality::create(['name' =>'San Pedro','departament_id'=>1]);
        Municipality::create(['name' =>'San Pedro','departament_id'=>22]);
        Municipality::create(['name' =>'San Pedro','departament_id'=>24]);
        Municipality::create(['name' =>'San Pedro de Cartago','departament_id'=>17]);
        Municipality::create(['name' =>'San Pedro de Urabá','departament_id'=>1]);
        Municipality::create(['name' =>'San Pelayo','departament_id'=>10]);
        Municipality::create(['name' =>'San Rafael','departament_id'=>1]);
        Municipality::create(['name' =>'San Roque','departament_id'=>1]);
        Municipality::create(['name' =>'San Sebastián','departament_id'=>8]);
        Municipality::create(['name' =>'San Sebastián de Buenavista','departament_id'=>15]);
        Municipality::create(['name' =>'San Vicente','departament_id'=>1]);
        Municipality::create(['name' =>'San Vicente del Caguán','departament_id'=>7]);
        Municipality::create(['name' =>'San Vicente del Chucurí','departament_id'=>21]);
        Municipality::create(['name' =>'San Zenón','departament_id'=>15]);
        Municipality::create(['name' =>'Sandoná','departament_id'=>17]);
        Municipality::create(['name' =>'Santa Ana','departament_id'=>15]);
        Municipality::create(['name' =>'Santa Bárbara','departament_id'=>1]);
        Municipality::create(['name' =>'Santa Bárbara','departament_id'=>21]);
        Municipality::create(['name' =>'Santa Bárbara (Iscuandé)','departament_id'=>17]);
        Municipality::create(['name' =>'Santa Bárbara de Pinto','departament_id'=>15]);
        Municipality::create(['name' =>'Santa Catalina','departament_id'=>4]);
        Municipality::create(['name' =>'Santa Fé de Antioquia','departament_id'=>1]);
        Municipality::create(['name' =>'Santa Genoveva de Docorodó','departament_id'=>12]);
        Municipality::create(['name' =>'Santa Helena del Opón','departament_id'=>21]);
        Municipality::create(['name' =>'Santa Isabel','departament_id'=>23]);
        Municipality::create(['name' =>'Santa Lucía','departament_id'=>2]);
        Municipality::create(['name' =>'Santa Marta','departament_id'=>15]);
        Municipality::create(['name' =>'Santa María','departament_id'=>5]);
        Municipality::create(['name' =>'Santa María','departament_id'=>13]);
        Municipality::create(['name' =>'Santa Rosa','departament_id'=>4]);
        Municipality::create(['name' =>'Santa Rosa','departament_id'=>8]);
        Municipality::create(['name' =>'Santa Rosa de Cabal','departament_id'=>20]);
        Municipality::create(['name' =>'Santa Rosa de Osos','departament_id'=>1]);
        Municipality::create(['name' =>'Santa Rosa de Viterbo','departament_id'=>5]);
        Municipality::create(['name' =>'Santa Rosa del Sur','departament_id'=>4]);
        Municipality::create(['name' =>'Santa Rosalía','departament_id'=>33]);
        Municipality::create(['name' =>'Santa Sofía','departament_id'=>5]);
        Municipality::create(['name' =>'Santana','departament_id'=>5]);
        Municipality::create(['name' =>'Santander de Quilichao','departament_id'=>8]);
        Municipality::create(['name' =>'Santiago','departament_id'=>18]);
        Municipality::create(['name' =>'Santiago','departament_id'=>27]);
        Municipality::create(['name' =>'Santo Domingo','departament_id'=>1]);
        Municipality::create(['name' =>'Santo Tomás','departament_id'=>2]);
        Municipality::create(['name' =>'Santuario','departament_id'=>1]);
        Municipality::create(['name' =>'Santuario','departament_id'=>20]);
        Municipality::create(['name' =>'Sapuyes','departament_id'=>17]);
        Municipality::create(['name' =>'Saravena','departament_id'=>25]);
        Municipality::create(['name' =>'Sardinata','departament_id'=>18]);
        Municipality::create(['name' =>'Sasaima','departament_id'=>11]);
        Municipality::create(['name' =>'Sativanorte','departament_id'=>5]);
        Municipality::create(['name' =>'Sativasur','departament_id'=>5]);
        Municipality::create(['name' =>'Segovia','departament_id'=>1]);
        Municipality::create(['name' =>'Sesquilé','departament_id'=>11]);
        Municipality::create(['name' =>'Sevilla','departament_id'=>24]);
        Municipality::create(['name' =>'Siachoque','departament_id'=>5]);
        Municipality::create(['name' =>'Sibaté','departament_id'=>11]);
        Municipality::create(['name' =>'Sibundoy','departament_id'=>27]);
        Municipality::create(['name' =>'Silos','departament_id'=>18]);
        Municipality::create(['name' =>'Silvania','departament_id'=>11]);
        Municipality::create(['name' =>'Silvia','departament_id'=>8]);
        Municipality::create(['name' =>'Simacota','departament_id'=>21]);
        Municipality::create(['name' =>'Simijaca','departament_id'=>11]);
        Municipality::create(['name' =>'Simití','departament_id'=>4]);
        Municipality::create(['name' =>'Sincelejo','departament_id'=>22]);
        Municipality::create(['name' =>'Sincé','departament_id'=>22]);
        Municipality::create(['name' =>'Sipí','departament_id'=>12]);
        Municipality::create(['name' =>'Sitionuevo','departament_id'=>15]);
        Municipality::create(['name' =>'Soacha','departament_id'=>11]);
        Municipality::create(['name' =>'Soatá','departament_id'=>5]);
        Municipality::create(['name' =>'Socha','departament_id'=>5]);
        Municipality::create(['name' =>'Socorro','departament_id'=>21]);
        Municipality::create(['name' =>'Socotá','departament_id'=>5]);
        Municipality::create(['name' =>'Sogamoso','departament_id'=>5]);
        Municipality::create(['name' =>'Solano','departament_id'=>7]);
        Municipality::create(['name' =>'Soledad','departament_id'=>2]);
        Municipality::create(['name' =>'Solita','departament_id'=>7]);
        Municipality::create(['name' =>'Somondoco','departament_id'=>5]);
        Municipality::create(['name' =>'Sonsón','departament_id'=>1]);
        Municipality::create(['name' =>'Sopetrán','departament_id'=>1]);
        Municipality::create(['name' =>'Soplaviento','departament_id'=>4]);
        Municipality::create(['name' =>'Sopó','departament_id'=>11]);
        Municipality::create(['name' =>'Sora','departament_id'=>5]);
        Municipality::create(['name' =>'Soracá','departament_id'=>5]);
        Municipality::create(['name' =>'Sotaquirá','departament_id'=>5]);
        Municipality::create(['name' =>'Sotara (Paispamba)','departament_id'=>8]);
        Municipality::create(['name' =>'Sotomayor (Los Andes)','departament_id'=>17]);
        Municipality::create(['name' =>'Suaita','departament_id'=>21]);
        Municipality::create(['name' =>'Suan','departament_id'=>2]);
        Municipality::create(['name' =>'Suaza','departament_id'=>13]);
        Municipality::create(['name' =>'Subachoque','departament_id'=>11]);
        Municipality::create(['name' =>'Sucre','departament_id'=>8]);
        Municipality::create(['name' =>'Sucre','departament_id'=>21]);
        Municipality::create(['name' =>'Sucre','departament_id'=>22]);
        Municipality::create(['name' =>'Suesca','departament_id'=>11]);
        Municipality::create(['name' =>'Supatá','departament_id'=>11]);
        Municipality::create(['name' =>'Supía','departament_id'=>6]);
        Municipality::create(['name' =>'Suratá','departament_id'=>21]);
        Municipality::create(['name' =>'Susa','departament_id'=>11]);
        Municipality::create(['name' =>'Susacón','departament_id'=>5]);
        Municipality::create(['name' =>'Sutamarchán','departament_id'=>5]);
        Municipality::create(['name' =>'Sutatausa','departament_id'=>11]);
        Municipality::create(['name' =>'Sutatenza','departament_id'=>5]);
        Municipality::create(['name' =>'Suárez','departament_id'=>8]);
        Municipality::create(['name' =>'Suárez','departament_id'=>23]);
        Municipality::create(['name' =>'Sácama','departament_id'=>26]);
        Municipality::create(['name' =>'Sáchica','departament_id'=>5]);
        Municipality::create(['name' =>'Tabio','departament_id'=>11]);
        Municipality::create(['name' =>'Tadó','departament_id'=>12]);
        Municipality::create(['name' =>'Talaigua Nuevo','departament_id'=>4]);
        Municipality::create(['name' =>'Tamalameque','departament_id'=>9]);
        Municipality::create(['name' =>'Tame','departament_id'=>25]);
        Municipality::create(['name' =>'Taminango','departament_id'=>17]);
        Municipality::create(['name' =>'Tangua','departament_id'=>17]);
        Municipality::create(['name' =>'Taraira','departament_id'=>32]);
        Municipality::create(['name' =>'Tarazá','departament_id'=>1]);
        Municipality::create(['name' =>'Tarqui','departament_id'=>13]);
        Municipality::create(['name' =>'Tarso','departament_id'=>1]);
        Municipality::create(['name' =>'Tasco','departament_id'=>5]);
        Municipality::create(['name' =>'Tauramena','departament_id'=>26]);
        Municipality::create(['name' =>'Tausa','departament_id'=>11]);
        Municipality::create(['name' =>'Tello','departament_id'=>13]);
        Municipality::create(['name' =>'Tena','departament_id'=>11]);
        Municipality::create(['name' =>'Tenerife','departament_id'=>15]);
        Municipality::create(['name' =>'Tenjo','departament_id'=>11]);
        Municipality::create(['name' =>'Tenza','departament_id'=>5]);
        Municipality::create(['name' =>'Teorama','departament_id'=>18]);
        Municipality::create(['name' =>'Teruel','departament_id'=>13]);
        Municipality::create(['name' =>'Tesalia','departament_id'=>13]);
        Municipality::create(['name' =>'Tibacuy','departament_id'=>11]);
        Municipality::create(['name' =>'Tibaná','departament_id'=>5]);
        Municipality::create(['name' =>'Tibasosa','departament_id'=>5]);
        Municipality::create(['name' =>'Tibirita','departament_id'=>11]);
        Municipality::create(['name' =>'Tibú','departament_id'=>18]);
        Municipality::create(['name' =>'Tierralta','departament_id'=>10]);
        Municipality::create(['name' =>'Timaná','departament_id'=>13]);
        Municipality::create(['name' =>'Timbiquí','departament_id'=>8]);
        Municipality::create(['name' =>'Timbío','departament_id'=>8]);
        Municipality::create(['name' =>'Tinjacá','departament_id'=>5]);
        Municipality::create(['name' =>'Tipacoque','departament_id'=>5]);
        Municipality::create(['name' =>'Tiquisio (Puerto Rico)','departament_id'=>4]);
        Municipality::create(['name' =>'Titiribí','departament_id'=>1]);
        Municipality::create(['name' =>'Toca','departament_id'=>5]);
        Municipality::create(['name' =>'Tocaima','departament_id'=>11]);
        Municipality::create(['name' =>'Tocancipá','departament_id'=>11]);
        Municipality::create(['name' =>'Toguí','departament_id'=>5]);
        Municipality::create(['name' =>'Toledo','departament_id'=>1]);
        Municipality::create(['name' =>'Toledo','departament_id'=>18]);
        Municipality::create(['name' =>'Tolú','departament_id'=>22]);
        Municipality::create(['name' =>'Tolú Viejo','departament_id'=>22]);
        Municipality::create(['name' =>'Tona','departament_id'=>21]);
        Municipality::create(['name' =>'Topagá','departament_id'=>5]);
        Municipality::create(['name' =>'Topaipí','departament_id'=>11]);
        Municipality::create(['name' =>'Toribío','departament_id'=>8]);
        Municipality::create(['name' =>'Toro','departament_id'=>24]);
        Municipality::create(['name' =>'Tota','departament_id'=>5]);
        Municipality::create(['name' =>'Totoró','departament_id'=>8]);
        Municipality::create(['name' =>'Trinidad','departament_id'=>26]);
        Municipality::create(['name' =>'Trujillo','departament_id'=>24]);
        Municipality::create(['name' =>'Tubará','departament_id'=>2]);
        Municipality::create(['name' =>'Tuchín','departament_id'=>10]);
        Municipality::create(['name' =>'Tulúa','departament_id'=>24]);
        Municipality::create(['name' =>'Tumaco','departament_id'=>17]);
        Municipality::create(['name' =>'Tunja','departament_id'=>5]);
        Municipality::create(['name' =>'Tunungua','departament_id'=>5]);
        Municipality::create(['name' =>'Turbaco','departament_id'=>4]);
        Municipality::create(['name' =>'Turbaná','departament_id'=>4]);
        Municipality::create(['name' =>'Turbo','departament_id'=>1]);
        Municipality::create(['name' =>'Turmequé','departament_id'=>5]);
        Municipality::create(['name' =>'Tuta','departament_id'=>5]);
        Municipality::create(['name' =>'Tutasá','departament_id'=>5]);
        Municipality::create(['name' =>'Támara','departament_id'=>26]);
        Municipality::create(['name' =>'Támesis','departament_id'=>1]);
        Municipality::create(['name' =>'Túquerres','departament_id'=>17]);
        Municipality::create(['name' =>'Ubalá','departament_id'=>11]);
        Municipality::create(['name' =>'Ubaque','departament_id'=>11]);
        Municipality::create(['name' =>'Ubaté','departament_id'=>11]);
        Municipality::create(['name' =>'Ulloa','departament_id'=>24]);
        Municipality::create(['name' =>'Une','departament_id'=>11]);
        Municipality::create(['name' =>'Unguía','departament_id'=>12]);
        Municipality::create(['name' =>'Unión Panamericana (ÁNIMAS)','departament_id'=>12]);
        Municipality::create(['name' =>'Uramita','departament_id'=>1]);
        Municipality::create(['name' =>'Uribe','departament_id'=>16]);
        Municipality::create(['name' =>'Uribia','departament_id'=>14]);
        Municipality::create(['name' =>'Urrao','departament_id'=>1]);
        Municipality::create(['name' =>'Urumita','departament_id'=>14]);
        Municipality::create(['name' =>'Usiacuri','departament_id'=>2]);
        Municipality::create(['name' =>'Valdivia','departament_id'=>1]);
        Municipality::create(['name' =>'Valencia','departament_id'=>10]);
        Municipality::create(['name' =>'Valle de San José','departament_id'=>21]);
        Municipality::create(['name' =>'Valle de San Juan','departament_id'=>23]);
        Municipality::create(['name' =>'Valle del Guamuez','departament_id'=>27]);
        Municipality::create(['name' =>'Valledupar','departament_id'=>9]);
        Municipality::create(['name' =>'Valparaiso','departament_id'=>1]);
        Municipality::create(['name' =>'Valparaiso','departament_id'=>7]);
        Municipality::create(['name' =>'Vegachí','departament_id'=>1]);
        Municipality::create(['name' =>'Venadillo','departament_id'=>23]);
        Municipality::create(['name' =>'Venecia','departament_id'=>1]);
        Municipality::create(['name' =>'Venecia (Ospina Pérez)','departament_id'=>11]);
        Municipality::create(['name' =>'Ventaquemada','departament_id'=>5]);
        Municipality::create(['name' =>'Vergara','departament_id'=>11]);
        Municipality::create(['name' =>'Versalles','departament_id'=>24]);
        Municipality::create(['name' =>'Vetas','departament_id'=>21]);
        Municipality::create(['name' =>'Viani','departament_id'=>11]);
        Municipality::create(['name' =>'Vigía del Fuerte','departament_id'=>1]);
        Municipality::create(['name' =>'Vijes','departament_id'=>24]);
        Municipality::create(['name' =>'Villa Caro','departament_id'=>18]);
        Municipality::create(['name' =>'Villa Rica','departament_id'=>8]);
        Municipality::create(['name' =>'Villa de Leiva','departament_id'=>5]);
        Municipality::create(['name' =>'Villa del Rosario','departament_id'=>18]);
        Municipality::create(['name' =>'Villagarzón','departament_id'=>27]);
        Municipality::create(['name' =>'Villagómez','departament_id'=>11]);
        Municipality::create(['name' =>'Villahermosa','departament_id'=>23]);
        Municipality::create(['name' =>'Villamaría','departament_id'=>6]);
        Municipality::create(['name' =>'Villanueva','departament_id'=>4]);
        Municipality::create(['name' =>'Villanueva','departament_id'=>14]);
        Municipality::create(['name' =>'Villanueva','departament_id'=>21]);
        Municipality::create(['name' =>'Villanueva','departament_id'=>26]);
        Municipality::create(['name' =>'Villapinzón','departament_id'=>11]);
        Municipality::create(['name' =>'Villarrica','departament_id'=>23]);
        Municipality::create(['name' =>'Villavicencio','departament_id'=>16]);
        Municipality::create(['name' =>'Villavieja','departament_id'=>13]);
        Municipality::create(['name' =>'Villeta','departament_id'=>11]);
        Municipality::create(['name' =>'Viotá','departament_id'=>11]);
        Municipality::create(['name' =>'Viracachá','departament_id'=>5]);
        Municipality::create(['name' =>'Vista Hermosa','departament_id'=>16]);
        Municipality::create(['name' =>'Viterbo','departament_id'=>6]);
        Municipality::create(['name' =>'Vélez','departament_id'=>21]);
        Municipality::create(['name' =>'Yacopí','departament_id'=>11]);
        Municipality::create(['name' =>'Yacuanquer','departament_id'=>17]);
        Municipality::create(['name' =>'Yaguará','departament_id'=>13]);
        Municipality::create(['name' =>'Yalí','departament_id'=>1]);
        Municipality::create(['name' =>'Yarumal','departament_id'=>1]);
        Municipality::create(['name' =>'Yolombó','departament_id'=>1]);
        Municipality::create(['name' =>'Yondó (Casabe)','departament_id'=>1]);
        Municipality::create(['name' =>'Yopal','departament_id'=>26]);
        Municipality::create(['name' =>'Yotoco','departament_id'=>24]);
        Municipality::create(['name' =>'Yumbo','departament_id'=>24]);
        Municipality::create(['name' =>'Zambrano','departament_id'=>4]);
        Municipality::create(['name' =>'Zapatoca','departament_id'=>21]);
        Municipality::create(['name' =>'Zapayán (PUNTA DE PIEDRAS)','departament_id'=>15]);
        Municipality::create(['name' =>'Zaragoza','departament_id'=>1]);
        Municipality::create(['name' =>'Zarzal','departament_id'=>24]);
        Municipality::create(['name' =>'Zetaquirá','departament_id'=>5]);
        Municipality::create(['name' =>'Zipacón','departament_id'=>11]);
        Municipality::create(['name' =>'Zipaquirá','departament_id'=>11]);
        Municipality::create(['name' =>'Zona Bananera (PRADO - SEVILLA)','departament_id'=>15]);
        Municipality::create(['name' =>'Ábrego','departament_id'=>18]);
        Municipality::create(['name' =>'Íquira','departament_id'=>13]);
        Municipality::create(['name' =>'Úmbita','departament_id'=>5]);
        Municipality::create(['name' =>'Útica','departament_id'=>11]);
        Municipality::create(['name' =>'Ciudad Bolívar','departament_id'=>1]);
        Municipality::create(['name' =>'Guadalajara de Buga','departament_id'=>24]);
        Municipality::create(['name' =>'Calima','departament_id'=>24]);
        Municipality::create(['name' =>'El carmen de viboral','departament_id'=>1]);
        Municipality::create(['name' =>'El Santuario','departament_id'=>1]);
        Municipality::create(['name' =>'San José de la Montaña','departament_id'=>1]);
        Municipality::create(['name' =>'Santafé de Antioquía','departament_id'=>1]);
        Municipality::create(['name' =>'Pasto','departament_id'=>17]);
        Municipality::create(['name' =>'El litorial del San Juan','departament_id'=>12]);
        Municipality::create(['name' =>'Aldana','departament_id'=>17]);
        Municipality::create(['name' =>'Cuaspud','departament_id'=>17]);
        Municipality::create(['name' =>'Funes','departament_id'=>17]);
        Municipality::create(['name' =>'El Carmen de Chucurí','departament_id'=>21]);
        Municipality::create(['name' =>'Santa Bárbara','departament_id'=>17]);
        Municipality::create(['name' =>'Santa Cruz','departament_id'=>17]);
        Municipality::create(['name' =>'Roberto Payán','departament_id'=>17]);
        Municipality::create(['name' =>'Los Andes','departament_id'=>17]);
        Municipality::create(['name' =>'Magüí Payán','departament_id'=>17]);
        Municipality::create(['name' =>'Mallama','departament_id'=>17]);
    }
}
